services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: github_repo_search_api:latest
    container_name: github_repo_search_api
    ports:
      - "8000:8000"
    volumes:
      - ./github_repo_search_api/static:/app/github_repo_search_api/static
    environment:
      GITHUB_REPO_SEARCH_API_HOST: 0.0.0.0
      GITHUB_REPO_SEARCH_API_PORT: 8000

