services:
  api:
    ports:
      # Exposes application port.
    - "8000:8000"
    build:
      context: .
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      GITHUB_REPO_SEARCH_API_RELOAD: "True"
